config/routes.rb
FantasyCycling::Application.routes.draw do

  resources :cyclists

  namespace :admin do
  match '/' => 'users#index'
  resources :users
end

  resources :teams

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  # attr_accessible :title, :body


  belongs_to :team
  belongs_to :cyclist
  
end

app/models/cyclist.rb
class Cyclist < ActiveRecord::Base
  attr_accessible :name, :value

  has_many :teammates
  has_many :teams, :through => :teammates
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true

  belongs_to :user
  validates :user_id, presence: true

  has_many :teammates
  has_many :cyclists, :through => :teammates

end

app/models/teammates.rb
class Teammates < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         #:recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :teams, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cyclists_controller.rb
class CyclistsController < ApplicationController
  # GET /cyclists
  # GET /cyclists.json
  def index
    @cyclists = Cyclist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cyclists }
    end
  end

  # GET /cyclists/1
  # GET /cyclists/1.json
  def show
    @cyclist = Cyclist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cyclist }
    end
  end

  # GET /cyclists/new
  # GET /cyclists/new.json
  def new
    @cyclist = Cyclist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cyclist }
    end
  end

  # GET /cyclists/1/edit
  def edit
    @cyclist = Cyclist.find(params[:id])
  end

  # POST /cyclists
  # POST /cyclists.json
  def create
    @cyclist = Cyclist.new(params[:cyclist])

    respond_to do |format|
      if @cyclist.save
        format.html { redirect_to @cyclist, notice: 'Cyclist was successfully created.' }
        format.json { render json: @cyclist, status: :created, location: @cyclist }
      else
        format.html { render action: "new" }
        format.json { render json: @cyclist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cyclists/1
  # PUT /cyclists/1.json
  def update
    @cyclist = Cyclist.find(params[:id])

    respond_to do |format|
      if @cyclist.update_attributes(params[:cyclist])
        format.html { redirect_to @cyclist, notice: 'Cyclist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cyclist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cyclists/1
  # DELETE /cyclists/1.json
  def destroy
    @cyclist = Cyclist.find(params[:id])
    @cyclist.destroy

    respond_to do |format|
      format.html { redirect_to cyclists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = current_user.teams.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = current_user.teams.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = current_user.teams.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = current_user.teams.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = current_user.teams.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cyclists_helper.rb
module CyclistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/cyclists/_cyclist.html.erb
 <%# if current_user == team.user %>

<tr>
    <td><%= cyclist.name %></td>

    <td><%= link_to 'View Cyclist', cyclist %></td>
    <td><%= link_to 'Edit Cyclist', edit_cyclist_path(cyclist) %></td>
    <td><%= link_to 'Delete Cyclist', cyclist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 </tr>
 <%# end %>

 

app/views/cyclists/_form.html.erb
<%= simple_form_for(@cyclist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cyclists/edit.html.erb
<h1>Editing cyclist</h1>

<%= render 'form' %>

<%= link_to 'Show', @cyclist %> |
<%= link_to 'Back', cyclists_path %>

app/views/cyclists/index.html.erb
<h1>Listing Cyclists</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Team Name</th>
      <th>Value</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<tbody>
  <%= render @cyclists %>
</tbody>
  
</table>

<br />

<%= link_to 'New Cyclist', new_cyclist_path %>

app/views/cyclists/new.html.erb
<h1>New Cyclist</h1>

<%= render 'form' %>

<%= link_to 'Back', cyclists_path %>

app/views/cyclists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <h2>
  						<%= @cyclist.name %>
            </h2>
            <p>
              <b>Value:</b>
  							<%= @cyclist.value %>
            </p>
            <%# if current_user == @cyclist.user %>

            <%= link_to 'Edit', edit_cyclist_path(@cyclist) %> |

            <%# end %>
            <%= link_to 'Back', cyclist_path %>

        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
	<div class="footer">
		<small>
	Lovingly made in the heart of New York City.
		</small>
	</div>

app/views/layouts/_header.html.erb
	<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
    	<div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <%= link_to "Crankturn", root_path, class: "brand" %>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    	<ul class="nav">
	   		<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About Us", about_path %></li>
			</ul>
			 <ul class="nav pull-right">
          <% if user_signed_in? %>


        <li><%= link_to "Cyclist +", new_cyclist_path %></li>
        <li><%= link_to "Add Team", new_team_path %></li>
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li class="navbar-text"> Welcome <%= current_user.name %> </li>

        <% else %>
	   		  <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
			</ul>

    </div>
    </div>
    </div>
    </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Crankturn Fantasy Cycling</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<%= render 'layouts/header' %>
	<div class ="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Crankturn Fantasy Cycling</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<%= render 'layouts/header' %>
	<div class ="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1> About Page </h1>

		
		<p>
				Crankturn is the newest and best fantasy cycling site out there!
		</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
        
   <h2>
    <%= link_to "My Teams", teams_path %>
   </h2>

    <h2>My Standings</h2>

    


 <% else %>

	<div class="hero-unit">
		<h1>Crankturn Fantasy Cycling!</h1>
		
		<p>
		</br>

			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-large" %>

		</p>
	</div>
<% end %>